// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prog7312_MunicipalityApp_ST10299399.Data;

#nullable disable

namespace Prog7312_MunicipalityApp_ST10299399.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Prog7312_MunicipalityApp_ST10299399.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Environment",
                            Description = "Join us for a community cleanup event to keep our neighborhood beautiful.",
                            EventDate = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/images/cleanup.jpg",
                            Location = "Central Park",
                            PostedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Community Cleanup"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Market",
                            Description = "Fresh produce and local goods available at the weekly farmers market.",
                            EventDate = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/images/farmers_market.jpg",
                            Location = "Town Square",
                            PostedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Farmers Market"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Art",
                            Description = "Experience local art and live music in the park.",
                            EventDate = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://example.com/images/art_in_park.jpg",
                            Location = "Riverside Park",
                            PostedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Art in the Park"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
